"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
const fields=["Sphere","Cylinder","Axis","Add"] as const;
const powers=Array.from({length:161},(_,i)=>(-20+i*.25));
const formatPower=(n:number)=>n===0?"0.00":`${n>0?"+":""}${n.toFixed(2)}`;
const fieldOptions=(field:string)=>field==="Axis"?Array.from({length:180},(_,i)=>String(i)):field==="Add"?Array.from({length:17},(_,i)=>formatPower(i*.25)):powers.map(formatPower);
const defaults=Object.fromEntries(["OD","OS"].flatMap(eye=>fields.map(f=>[`${eye}-${f}`,f==="Axis"?"0":"0.00"]))) as Record<string,string>;
type RecordItem={id:number;firstInitial:string;lastName:string;previousJobIds:string[];currentJobId:string;rx:Record<string,string>;createdAt:string;updatedAt:string};
const readable=(x:string)=>new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(x));
export default function PatientApp(){
 const [auth,setAuth]=useState(false),[pin,setPin]=useState(""),[error,setError]=useState(""),[records,setRecords]=useState<RecordItem[]>([]),[selected,setSelected]=useState<RecordItem|null>(null),[query,setQuery]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [form,setForm]=useState({firstInitial:"",lastName:"",currentJobId:"",previousActive:false,previousJobIds:[""] as string[],rx:{...defaults}});
 const load=async()=>{const r=await fetch("/api/records",{cache:"no-store"});if(r.status===401)return setAuth(false);if(r.ok)setRecords(await r.json())};
 useEffect(()=>{fetch("/api/session").then(r=>r.json()).then(d=>{setAuth(Boolean(d.authenticated));if(d.authenticated)load()})},[]);
 const filtered=useMemo(()=>{const n=query.toLowerCase().trim();return n?records.filter(r=>`${r.firstInitial} ${r.lastName} ${r.currentJobId} ${r.previousJobIds.join(" ")}`.toLowerCase().includes(n)):records},[records,query]);
 const login=async(e:FormEvent)=>{e.preventDefault();const r=await fetch("/api/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({pin})});if(!r.ok)return setError("Incorrect access code.");setAuth(true);setPin("");load()};
 const save=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setMessage("");const payload={...form,previousJobIds:form.previousActive?form.previousJobIds.filter(Boolean):[]};const r=await fetch("/api/records",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});setBusy(false);if(!r.ok)return setMessage("The record could not be saved. Check the Job ID.");const saved=await r.json() as RecordItem;setMessage(`Job ${saved.currentJobId} saved.`);setSelected(saved);setForm({firstInitial:"",lastName:"",currentJobId:"",previousActive:false,previousJobIds:[""],rx:{...defaults}});load()};
 if(!auth)return <main className="login-shell"><form className="login-card" onSubmit={login}><div className="brand-mark">TEP</div><p className="eyebrow">That Eye Place</p><h1>PatientUpdate</h1><p className="muted">Enter the temporary access code.</p><label>Access code<input inputMode="numeric" type="password" value={pin} onChange={e=>setPin(e.target.value)} autoFocus/></label>{error&&<p className="error">{error}</p>}<button className="primary">Sign in</button></form></main>;
 return <main className="app-shell"><header className="topbar no-print"><div><p className="eyebrow">That Eye Place</p><h1>PatientUpdate</h1></div><button className="quiet" onClick={async()=>{await fetch("/api/logout",{method:"POST"});setAuth(false)}}>Sign out</button></header>
 <section className="workspace no-print"><form className="panel form-panel" onSubmit={save}><div className="panel-heading"><div><p className="eyebrow">New record</p><h2>Patient job update</h2></div></div><div className="identity-grid"><label>First initial<input required maxLength={1} value={form.firstInitial} onChange={e=>setForm({...form,firstInitial:e.target.value.toUpperCase()})}/></label><label>Last name<input required value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/></label><label>Current Job ID<input required value={form.currentJobId} onChange={e=>setForm({...form,currentJobId:e.target.value})}/></label></div>
 <label className="toggle"><input type="checkbox" checked={form.previousActive} onChange={e=>setForm({...form,previousActive:e.target.checked})}/><span>Include previous Job ID(s)</span></label>{form.previousActive&&<div className="previous-list">{form.previousJobIds.map((x,i)=><div className="previous-row" key={i}><input aria-label={`Previous Job ID ${i+1}`} placeholder={`Previous Job ID ${i+1}`} value={x} onChange={e=>{const a=[...form.previousJobIds];a[i]=e.target.value;setForm({...form,previousJobIds:a})}}/>{form.previousJobIds.length>1&&<button type="button" className="remove" onClick={()=>setForm({...form,previousJobIds:form.previousJobIds.filter((_,j)=>j!==i)})}>Remove</button>}</div>)}<button type="button" className="add" onClick={()=>setForm({...form,previousJobIds:[...form.previousJobIds,""]})}>+ Add another previous Job ID</button></div>}
 <div className="rx-wrap"><div className="rx-title"><h3>Prescription update</h3><small>Sphere/Cylinder: ±20.00 · Axis: 0–179 · Add: 0.00–+4.00</small></div><div className="rx-table"><div className="rx-head"></div>{fields.map(f=><div className="rx-head" key={f}>{f}</div>)}{["OD","OS"].map(eye=><div className="rx-row" key={eye}><div className="eye">{eye}</div>{fields.map(f=><select aria-label={`${eye} ${f}`} key={f} value={form.rx[`${eye}-${f}`]} onChange={e=>setForm({...form,rx:{...form.rx,[`${eye}-${f}`]:e.target.value}})}>{fieldOptions(f).map(value=><option value={value} key={value}>{value}</option>)}</select>)}</div>)}</div></div>
 <button disabled={busy} className="primary save">{busy?"Saving…":"Save record & timestamp"}</button>{message&&<p className="success">{message}</p>}</form>
 <section className="panel records"><div className="panel-heading"><div><p className="eyebrow">Shared records</p><h2>Saved updates</h2></div><span className="count">{filtered.length}</span></div><input type="search" placeholder="Search name or Job ID" value={query} onChange={e=>setQuery(e.target.value)}/><div className="record-list">{filtered.map(r=><button className="record-row" key={r.id} onClick={()=>setSelected(r)}><span><strong>{r.firstInitial}. {r.lastName}</strong><small>Current Job {r.currentJobId}</small></span><time>{readable(r.updatedAt)}</time></button>)}{!filtered.length&&<p className="empty">No matching records.</p>}</div></section></section>
 {selected&&<section className="record-sheet"><div className="actions no-print"><button className="quiet" onClick={()=>setSelected(null)}>Close</button><button className="primary" onClick={()=>window.print()}>Print / Save PDF</button></div><div className="print-header"><p className="eyebrow">That Eye Place</p><h2>Patient Update Record</h2></div><dl><div><dt>Patient</dt><dd>{selected.firstInitial}. {selected.lastName}</dd></div><div><dt>Current Job ID</dt><dd>{selected.currentJobId}</dd></div><div><dt>Previous Job ID(s)</dt><dd>{selected.previousJobIds.length?selected.previousJobIds.join(", "):"None"}</dd></div><div><dt>Timestamp</dt><dd>{readable(selected.updatedAt)}</dd></div></dl><table><thead><tr><th></th>{fields.map(f=><th key={f}>{f}</th>)}</tr></thead><tbody>{["OD","OS"].map(eye=><tr key={eye}><th>{eye}</th>{fields.map(f=><td key={f}>{selected.rx[`${eye}-${f}`]}</td>)}</tr>)}</tbody></table><footer>Record created {readable(selected.createdAt)}</footer></section>}
 </main>}
